# This is a basic workflow to help you get started with Actions

name: SARIF_Upload

on:
  push:
    branches: [ "main", "drodriguezhdez/github_actions" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Upload SARIF reports
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: samples

